In [2]:
import pandas as pd

In [3]:
import pandas as pd

print("Notebook is working")

Notebook is working

In [5]:
import os
print(os.getcwd())

d:\test\notebooks

In [6]:
import pandas as pd

nav = pd.read_csv("../data/02_nav_history.csv")

print(nav.shape)
print(nav.columns)

nav.head()

(46000, 3)
Index(['amfi_code', 'date', 'nav'], dtype='object')

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [7]:
nav["date"] = pd.to_datetime(nav["date"])

nav.dtypes

amfi_code             int64
date         datetime64[ns]
nav                 float64
dtype: object

In [8]:
print(
    "Duplicate rows:",
    nav.duplicated().sum()
)

Duplicate rows: 0

In [9]:
print(
    "NAV <= 0:",
    (nav["nav"] <= 0).sum()
)

NAV <= 0: 0

In [10]:
nav.to_csv(
    "../data/processed/clean_nav.csv",
    index=False
)

print("clean_nav.csv saved")

clean_nav.csv saved

In [11]:
transactions = pd.read_csv(
    "../data/08_investor_transactions.csv"
)

print(transactions.shape)
print(transactions.columns)

transactions.head()

(32778, 13)
Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='object')

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [12]:
transactions.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [13]:
print("Duplicate rows:", transactions.duplicated().sum())

Duplicate rows: 0

In [14]:
print(transactions["transaction_type"].unique())

['SIP' 'Redemption' 'Lumpsum']

In [15]:
print("Duplicate rows:", transactions.duplicated().sum())

Duplicate rows: 0

In [16]:
print("Amount <= 0:", (transactions["amount_inr"] <= 0).sum())

Amount <= 0: 0

In [17]:
print(transactions["kyc_status"].value_counts())

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [18]:
transactions["transaction_date"] = pd.to_datetime(
    transactions["transaction_date"]
)

transactions.to_csv(
    "../data/processed/clean_transactions.csv",
    index=False
)

print("clean_transactions.csv saved")

clean_transactions.csv saved

In [19]:
performance = pd.read_csv(
    "../data/07_scheme_performance.csv"
)

print(performance.shape)
print(performance.columns)

performance.head()

(40, 19)
Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [20]:
performance.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [21]:
print("Duplicate rows:", performance.duplicated().sum())

Duplicate rows: 0

In [22]:
print(
    "Negative Sharpe Ratios:",
    (performance["sharpe_ratio"] < 0).sum()
)

Negative Sharpe Ratios: 0

In [23]:
print(
    "Outside range:",
    (
        (performance["expense_ratio_pct"] < 0.1)
        |
        (performance["expense_ratio_pct"] > 2.5)
    ).sum()
)

Outside range: 0

In [24]:
performance.to_csv(
    "../data/processed/clean_performance.csv",
    index=False
)

print("clean_performance.csv saved")

clean_performance.csv saved

In [25]:
import sqlite3

conn = sqlite3.connect(
    "../data/db/bluestock_mf.db"
)

print("Database created successfully")

Database created successfully

In [26]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../data/db/bluestock_mf.db")

nav = pd.read_csv("../data/processed/clean_nav.csv")
transactions = pd.read_csv("../data/processed/clean_transactions.csv")
performance = pd.read_csv("../data/processed/clean_performance.csv")

nav.to_sql(
    "nav_history",
    conn,
    if_exists="replace",
    index=False
)

transactions.to_sql(
    "transactions",
    conn,
    if_exists="replace",
    index=False
)

performance.to_sql(
    "performance",
    conn,
    if_exists="replace",
    index=False
)

print("All tables loaded successfully")

All tables loaded successfully

In [27]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

           name
0   nav_history
1  transactions
2   performance

In [28]:
query = """
SELECT *
FROM performance
LIMIT 5;
"""

pd.read_sql(query, conn)

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [29]:
query = """
SELECT
    scheme_name,
    fund_house,
    return_1yr_pct
FROM performance
ORDER BY return_1yr_pct DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

,scheme_name,fund_house,return_1yr_pct
0,ABSL Small Cap Fund - Regular - Growth,Aditya Birla Sun Life MF,24.93
1,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,24.56
2,Axis Small Cap Fund - Regular - Growth,Axis Mutual Fund,21.97
3,Nippon India Small Cap Fund - Regular - Growth,Nippon India MF,21.30
4,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,20.59

In [30]:
query = """
SELECT
    transaction_type,
    SUM(amount_inr) AS total_amount
FROM transactions
GROUP BY transaction_type;
"""

pd.read_sql(query, conn)

  transaction_type  total_amount
0          Lumpsum    2059821448
1       Redemption    1244525491
2              SIP     217233491

In [31]:
query = """
SELECT
    state,
    COUNT(*) AS transactions
FROM transactions
GROUP BY state
ORDER BY transactions DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

            state  transactions
0          Punjab          2965
1  Madhya Pradesh          2931
2      Tamil Nadu          2806
3         Gujarat          2780
4     West Bengal          2748
5         Haryana          2736
6       Telangana          2718
7   Uttar Pradesh          2695
8           Delhi          2677
9       Karnataka          2621